// <auto-generated />
using System;
using Herbzhub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Herbzhub.Data.Migrations
{
    [DbContext(typeof(DbApplicationContext))]
    [Migration("20240528005715_initnew")]
    partial class initnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Herbzhub.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New York City",
                            State = "New York",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3191)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Los Angeles",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3201)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicago",
                            State = "Illinois",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3203)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Houston",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3205)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phoenix",
                            State = "Arizona",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3207)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Philadelphia",
                            State = "Pennsylvania",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3211)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "San Antonio",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3213)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "San Diego",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3216)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dallas",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3217)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "San Jose",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3221)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Austin",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3223)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jacksonville",
                            State = "Florida",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3230)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fort Worth",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3233)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Columbus",
                            State = "Ohio",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3235)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "San Francisco",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3237)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlotte",
                            State = "North Carolina",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3238)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Indianapolis",
                            State = "Indiana",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3368)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Seattle",
                            State = "Washington",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3373)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denver",
                            State = "Colorado",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3375)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Washington",
                            State = "District of Columbia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3377)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Boston",
                            State = "Massachusetts",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3379)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "El Paso",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3381)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nashville",
                            State = "Tennessee",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3382)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Detroit",
                            State = "Michigan",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3384)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oklahoma City",
                            State = "Oklahoma",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3386)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Portland",
                            State = "Oregon",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3388)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Las Vegas",
                            State = "Nevada",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3389)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Memphis",
                            State = "Tennessee",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3391)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Louisville",
                            State = "Kentucky",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3393)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Baltimore",
                            State = "Maryland",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3395)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milwaukee",
                            State = "Wisconsin",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3396)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Albuquerque",
                            State = "New Mexico",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3398)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tucson",
                            State = "Arizona",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3400)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fresno",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3404)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sacramento",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3406)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kansas City",
                            State = "Missouri",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3407)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Long Beach",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3409)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mesa",
                            State = "Arizona",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3411)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Atlanta",
                            State = "Georgia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3413)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colorado Springs",
                            State = "Colorado",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3415)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virginia Beach",
                            State = "Virginia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3417)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Raleigh",
                            State = "North Carolina",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3419)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Omaha",
                            State = "Nebraska",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3421)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miami",
                            State = "Florida",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3423)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oakland",
                            State = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3424)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Minneapolis",
                            State = "Minnesota",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3426)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tulsa",
                            State = "Oklahoma",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3428)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wichita",
                            State = "Kansas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Orleans",
                            State = "Louisiana",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3432)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arlington",
                            State = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3433)
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.Counties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Andrew"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Atchison"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audrain"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Barry"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Barton"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bates"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Benton"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bollinger"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Boone"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Buchanan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Butler"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Caldwell"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Callaway"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Camden"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cape Girardeau"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Carroll"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Carter"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cass"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cedar"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Chariton"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Christian"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Clark"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Clay"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Clinton"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Cole"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Cooper"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Crawford"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Dade"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Dallas"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Daviess"
                        },
                        new
                        {
                            Id = 32,
                            Name = "DeKalb"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Dent"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Douglas"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Dunklin"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Franklin"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Gasconade"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Gentry"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Greene"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Grundy"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Harrison"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Henry"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Hickory"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Holt"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Howard"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Howell"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Jackson"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Jasper"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Jefferson"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Johnson"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Knox"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Laclede"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Lafayette"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Lawrence"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Lewis"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Linn"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Livingston"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Macon"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Madison"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Maries"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Marion"
                        },
                        new
                        {
                            Id = 64,
                            Name = "McDonald"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Mercer"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Miller"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Moniteau"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Monroe"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Montgomery"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Morgan"
                        },
                        new
                        {
                            Id = 72,
                            Name = "New Madrid"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Newton"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Nodaway"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Osage"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Ozark"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Pemiscot"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Perry"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Pettis"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Phelps"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Pike"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Platte"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Polk"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Pulaski"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Putnam"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Ralls"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Randolph"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Ray"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Reynolds"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Ripley"
                        },
                        new
                        {
                            Id = 92,
                            Name = "St. Charles"
                        },
                        new
                        {
                            Id = 93,
                            Name = "St. Clair"
                        },
                        new
                        {
                            Id = 94,
                            Name = "St. Francois"
                        },
                        new
                        {
                            Id = 95,
                            Name = "St. Louis"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Ste. Genevieve"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Saline"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Schuyler"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Scott"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Shannon"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Shelby"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Stoddard"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Sullivan"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Taney"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Vernon"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Warren"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Wayne"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Webster"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Worth"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Wright"
                        },
                        new
                        {
                            Id = 115,
                            Name = "City of St. Louis"
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "United States",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(1895)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canada",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(1902)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "United Kingdom",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(1903)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nigeria",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(1905)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Togo",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(1906)
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.ManufacturerDispensary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BusinessCityId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessEIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BusinessStateId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalBusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonalIdentificationId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateLicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCityId");

                    b.HasIndex("BusinessEIN")
                        .IsUnique();

                    b.HasIndex("BusinessEmail")
                        .IsUnique();

                    b.HasIndex("BusinessStateId");

                    b.HasIndex("PersonalIdentificationId");

                    b.HasIndex("StateLicenseNumber")
                        .IsUnique();

                    b.ToTable("ManufacturerDispensaries");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.PersonalIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CountiesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountiesId")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("PersonalIdentifications");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Manufacturer",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3820)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Manufacturer Driver",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3827)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Dispensary",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3829)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Customer Driver",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3831)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Customer",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(3833)
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.SMSVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthenticationEntityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("verification_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationEntityId")
                        .IsUnique();

                    b.ToTable("SMSVerificationCodes");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alabama",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2713)
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AK",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alaska",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2720)
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "AZ",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arizona",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2722)
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "AR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arkansas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2725)
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "California",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2727)
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "CO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colorado",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2732)
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "CT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Connecticut",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2734)
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "DE",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delaware",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2736)
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "FL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Florida",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2738)
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "GA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Georgia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2741)
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "HI",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hawaii",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2743)
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "ID",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Idaho",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2745)
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "IL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Illinois",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2747)
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "IN",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Indiana",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2749)
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "IA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iowa",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2751)
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "KS",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kansas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2753)
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "KY",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kentucky",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2755)
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "LA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Louisiana",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2759)
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "ME",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maine",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2761)
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "MD",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maryland",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2763)
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "MA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Massachusetts",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2776)
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "MI",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michigan",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2778)
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "MN",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Minnesota",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2780)
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "MS",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mississippi",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2782)
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "MO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Missouri",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2784)
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "MT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Montana",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2785)
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "NE",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nebraska",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2787)
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "NV",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nevada",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2789)
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "NH",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Hampshire",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2790)
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "NJ",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Jersey",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2792)
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "NM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Mexico",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2794)
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "NY",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New York",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2795)
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "NC",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "North Carolina",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2797)
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "ND",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "North Dakota",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2801)
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "OH",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ohio",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2802)
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "OK",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oklahoma",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2804)
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "OR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oregon",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2806)
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "PA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pennsylvania",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2808)
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "RI",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rhode Island",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2810)
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "SC",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "South Carolina",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2812)
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "SD",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "South Dakota",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2813)
                        },
                        new
                        {
                            Id = 42,
                            Abbreviation = "TN",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tennessee",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2815)
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "TX",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Texas",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2817)
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "UT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Utah",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2819)
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "VT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vermont",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2821)
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "VA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virginia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2822)
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "WA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Washington",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2824)
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "WV",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "West Virginia",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2826)
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "WI",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wisconsin",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2827)
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "WY",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wyoming",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 13, 740, DateTimeKind.Utc).AddTicks(2829)
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            HashPassword = "$2a$11$xjMsJnwbwlv4pDNSmm96H.DPZNlhX2mwtNN3eBGaB1ylZDTQ6cnwK",
                            UpdatedAt = new DateTime(2024, 5, 28, 0, 57, 14, 46, DateTimeKind.Utc).AddTicks(5323)
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Herbzhub.Data.Models.ManufacturerDispensary", b =>
                {
                    b.HasOne("Herbzhub.Data.Models.City", "BusinessCity")
                        .WithMany("ManufacturerDispensaries")
                        .HasForeignKey("BusinessCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.State", "BusinessState")
                        .WithMany()
                        .HasForeignKey("BusinessStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.PersonalIdentification", "PersonalIdentification")
                        .WithMany("ManufacturerDispensary")
                        .HasForeignKey("PersonalIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCity");

                    b.Navigation("BusinessState");

                    b.Navigation("PersonalIdentification");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.PersonalIdentification", b =>
                {
                    b.HasOne("Herbzhub.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.Counties", "counties")
                        .WithOne("PersonalIdentification")
                        .HasForeignKey("Herbzhub.Data.Models.PersonalIdentification", "CountiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.User", "User")
                        .WithOne("personalIdentifications")
                        .HasForeignKey("Herbzhub.Data.Models.PersonalIdentification", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("State");

                    b.Navigation("User");

                    b.Navigation("counties");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.SMSVerificationCode", b =>
                {
                    b.HasOne("Herbzhub.Data.Models.User", "authenticationEntity")
                        .WithOne("SMSVerificationCodes")
                        .HasForeignKey("Herbzhub.Data.Models.SMSVerificationCode", "AuthenticationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("authenticationEntity");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.UserRole", b =>
                {
                    b.HasOne("Herbzhub.Data.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Herbzhub.Data.Models.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.City", b =>
                {
                    b.Navigation("ManufacturerDispensaries");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.Counties", b =>
                {
                    b.Navigation("PersonalIdentification")
                        .IsRequired();
                });

            modelBuilder.Entity("Herbzhub.Data.Models.PersonalIdentification", b =>
                {
                    b.Navigation("ManufacturerDispensary");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.Role", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Herbzhub.Data.Models.User", b =>
                {
                    b.Navigation("SMSVerificationCodes")
                        .IsRequired();

                    b.Navigation("UserRole");

                    b.Navigation("personalIdentifications")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
