export const CustomCounties = [
  { name: 'Adair', id: 1 },
  { name: 'Andrew', id: 2 },
  { name: 'Atchison', id: 3 },
  { name: 'Audrain', id: 4 },
  { name: 'Barry', id: 5 },
  { name: 'Barton', id: 6 },
  { name: 'Bates', id: 7 },
  { name: 'Benton', id: 8 },
  { name: 'Bollinger', id: 9 },
  { name: 'Boone', id: 10 },
  { name: 'Buchanan', id: 11 },
  { name: 'Butler', id: 12 },
  { name: 'Caldwell', id: 13 },
  { name: 'Callaway', id: 14 },
  { name: 'Camden', id: 15 },
  { name: 'Cape Girardeau', id: 16 },
  { name: 'Carroll', id: 17 },
  { name: 'Carter', id: 18 },
  { name: 'Cass', id: 19 },
  { name: 'Cedar', id: 20 },
  { name: 'Chariton', id: 21 },
  { name: 'Christian', id: 22 },
  { name: 'Clark', id: 23 },
  { name: 'Clay', id: 24 },
  { name: 'Clinton', id: 25 },
  { name: 'Cole', id: 26 },
  { name: 'Cooper', id: 27 },
  { name: 'Crawford', id: 28 },
  { name: 'Dade', id: 29 },
  { name: 'Dallas', id: 30 },
  { name: 'Daviess', id: 31 },
  { name: 'DeKalb', id: 32 },
  { name: 'Dent', id: 33 },
  { name: 'Douglas', id: 34 },
  { name: 'Dunklin', id: 35 },
  { name: 'Franklin', id: 36 },
  { name: 'Gasconade', id: 37 },
  { name: 'Gentry', id: 38 },
  { name: 'Greene', id: 39 },
  { name: 'Grundy', id: 40 },
  { name: 'Harrison', id: 41 },
  { name: 'Henry', id: 42 },
  { name: 'Hickory', id: 43 },
  { name: 'Holt', id: 44 },
  { name: 'Howard', id: 45 },
  { name: 'Howell', id: 46 },
  { name: 'Iron', id: 47 },
  { name: 'Jackson', id: 48 },
  { name: 'Jasper', id: 49 },
  { name: 'Jefferson', id: 50 },
  { name: 'Johnson', id: 51 },
  { name: 'Knox', id: 52 },
  { name: 'Laclede', id: 53 },
  { name: 'Lafayette', id: 54 },
  { name: 'Lawrence', id: 55 },
  { name: 'Lewis', id: 56 },
  { name: 'Lincoln', id: 57 },
  { name: 'Linn', id: 58 },
  { name: 'Livingston', id: 59 },
  { name: 'Macon', id: 60 },
  { name: 'Madison', id: 61 },
  { name: 'Maries', id: 62 },
  { name: 'Marion', id: 63 },
  { name: 'McDonald', id: 64 },
  { name: 'Mercer', id: 65 },
  { name: 'Miller', id: 66 },
  { name: 'Mississippi', id: 67 },
  { name: 'Moniteau', id: 68 },
  { name: 'Monroe', id: 69 },
  { name: 'Montgomery', id: 70 },
  { name: 'Morgan', id: 71 },
  { name: 'New Madrid', id: 72 },
  { name: 'Newton', id: 73 },
  { name: 'Nodaway', id: 74 },
  { name: 'Oregon', id: 75 },
  { name: 'Osage', id: 76 },
  { name: 'Ozark', id: 77 },
  { name: 'Pemiscot', id: 78 },
  { name: 'Perry', id: 79 },
  { name: 'Pettis', id: 80 },
  { name: 'Phelps', id: 81 },
  { name: 'Pike', id: 82 },
  { name: 'Platte', id: 83 },
  { name: 'Polk', id: 84 },
  { name: 'Pulaski', id: 85 },
  { name: 'Putnam', id: 86 },
  { name: 'Ralls', id: 87 },
  { name: 'Randolph', id: 88 },
  { name: 'Ray', id: 89 },
  { name: 'Reynolds', id: 90 },
  { name: 'Ripley', id: 91 },
  { name: 'St. Charles', id: 92 },
  { name: 'St. Clair', id: 93 },
  { name: 'St. Francois', id: 94 },
  { name: 'St. Louis', id: 95 },
  { name: 'Ste. Genevieve', id: 96 },
  { name: 'Saline', id: 97 },
  { name: 'Schuyler', id: 98 },
  { name: 'Scotland', id: 99 },
  { name: 'Scott', id: 100 },
  { name: 'Shannon', id: 101 },
  { name: 'Shelby', id: 102 },
  { name: 'Stoddard', id: 103 },
  { name: 'Stone', id: 104 },
  { name: 'Sullivan', id: 105 },
  { name: 'Taney', id: 106 },
  { name: 'Texas', id: 107 },
  { name: 'Vernon', id: 108 },
  { name: 'Warren', id: 109 },
  { name: 'Washington', id: 110 },
  { name: 'Wayne', id: 111 },
  { name: 'Webster', id: 112 },
  { name: 'Worth', id: 113 },
  { name: 'Wright', id: 114 },
  { name: 'City of St. Louis', id: 115 },
];

export const CustomStates = [
  { name: 'Alabama', id: 1 },
  { name: 'Alaska', id: 2 },
  { name: 'Arizona', id: 3 },
  { name: 'Arkansas', id: 4 },
  { name: 'California', id: 5 },
  { name: 'Colorado', id: 6 },
  { name: 'Connecticut', id: 7 },
  { name: 'Delaware', id: 8 },
  { name: 'Florida', id: 9 },
  { name: 'Georgia', id: 10 },
  { name: 'Hawaii', id: 11 },
  { name: 'Idaho', id: 12 },
  { name: 'Illinois', id: 13 },
  { name: 'Indiana', id: 14 },
  { name: 'Iowa', id: 15 },
  { name: 'Kansas', id: 16 },
  { name: 'Kentucky', id: 17 },
  { name: 'Louisiana', id: 18 },
  { name: 'Maine', id: 19 },
  { name: 'Maryland', id: 20 },
  { name: 'Massachusetts', id: 21 },
  { name: 'Michigan', id: 22 },
  { name: 'Minnesota', id: 23 },
  { name: 'Mississippi', id: 24 },
  { name: 'Missouri', id: 25 },
  { name: 'Montana', id: 26 },
  { name: 'Nebraska', id: 27 },
  { name: 'Nevada', id: 28 },
  { name: 'New Hampshire', id: 29 },
  { name: 'New Jersey', id: 30 },
  { name: 'New Mexico', id: 31 },
  { name: 'New York', id: 32 },
  { name: 'North Carolina', id: 33 },
  { name: 'North Dakota', id: 34 },
  { name: 'Ohio', id: 35 },
  { name: 'Oklahoma', id: 36 },
  { name: 'Oregon', id: 37 },
  { name: 'Pennsylvania', id: 38 },
  { name: 'Rhode Island', id: 39 },
  { name: 'South Carolina', id: 40 },
  { name: 'South Dakota', id: 41 },
  { name: 'Tennessee', id: 42 },
  { name: 'Texas', id: 43 },
  { name: 'Utah', id: 44 },
  { name: 'Vermont', id: 45 },
  { name: 'Virginia', id: 46 },
  { name: 'Washington', id: 47 },
  { name: 'West Virginia', id: 48 },
  { name: 'Wisconsin', id: 49 },
  { name: 'Wyoming', id: 50 },
];

export const CustomOrganizationType = [
  { name: "Manufacturer", value: "manufacturer" },
  { name: "Dispensary", value: "dispensary" },
  { name: "Transporter", value: "transporter" }
];


export const logoIcon = require('../../assets/images/herbzhub_icon_152030.png');
export const logoText = require('../../assets/images/herbzhub_text_152030.png');
export const logoTextWhite = require('../../assets/images/HerbzHub-white.png');
