name: Deploy to Linode
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test Backend
        run: |
          # Build and test your .NET backend here

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create .ssh Directory
        run: mkdir -p ~/.ssh

      - name: Add Linode VM to known_hosts
        run: ssh-keyscan -H 172.232.11.46 >> ~/.ssh/known_hosts

      # React frontend deployment steps
      - name: Build React Frontend
        run: |
          cd frontend/web
          npm install && npm run build

      - name: Deploy React Frontend to Linode VM
        run: |
          sshpass -p "your_ssh_password" rsync -avzr -e "ssh -o StrictHostKeyChecking=no" front/web/build/ root@172.232.11.46:/var/www/herbzhubFrontend
